{  # data / 3 / 현물
    "B7_": "ETF호가잔량(B7)",  # data / 3 / ETF
    "BMT": "시간대별투자자매매추이",  # data / 3 / 현물
    "BM_": "업종별투자자별매매현황(BM)",  # data / 3 / 현물
    "C01": "선물주문체결",  # order / 3 / 선물
    "CD0": "상품선물실시간상하한가(D0)",  # data / 3 / 선물
    "DH1": "KOSPI시간외단일가호가잔량",  # data / 3 / 현물
    "DHA": "KOSDAQ시간외단일가호가잔량",  # data / 3 / 현물
    "DK3": "KOSDAQ시간외단일가체결",  # data / 3 / 현물
    "DS3": "KOSPI시간외단일가체결",  # data / 3 / 현물
    "DVI": "시간외단일가VI발동해제",  # data / 3 / 현물
    "EC0": "EUREX연계KP200지수옵션선물체결",  # order / 3 / 유렉스
    "EH0": "EUREX연계KP200지수옵션선물호가",  # data / 3 / 유렉스
    "ESN": "뉴ELW투자지표민감도",  # data / 3 / ELW
    "EU0": "EUX접수",  # order / 3 / 유렉스
    "EU1": "EUX체결",  # order / 3 / 유렉스
    "EU2": "EUX확인",  # order/ 3 / 유렉스
    "FC0": "KOSPI200선물체결(C0)",  # order / 3 / 현물
    "FD0": "KOSPI200선물실시간상하한가(D0)",  # data / 3 / 현물
    "FH0": "KOSPI200선물호가(H0)",  # data / 3 / 현물
    "FX0": "KOSPI200선물가격제한폭확대(X0)",  # data / 3 / 현물
    "H01": "선물주문정정취소",  # order / 3 / 선물
    "H1_": "KOSPI호가잔량(H1)",  # data / 3 / 현물
    "H2_": "KOSPI장전시간외호가잔량(H2)",  # data / 3 / 현물
    "h2_4ELW": "ELW장전시간외호가잔량(h2)",  # data / 3 / 현물
    "h3_4ELW": "ELW호가잔량(h3)",  # data / 3 / 현물
    "HA_": "KOSDAQ호가잔량(HA)",  # data / 3 / 현물
    "HB_": "KOSDAQ장전시간외호가잔량(HB)",  # data / 3 / 현물
    "I5_": "코스피ETF종목실시간NAV(I5)",  # data / 3 / ETF
    "IJ_": "지수(IJ)",  # data / 3 / 현물
    "JC0": "주식선물체결",  # order / 3 / 선물
    "JD0": "주식선물실시간상하한가",  # data / 3 / 선물
    "JH0": "주식선물호가",  # data / 3 / 선물
    "JIF": "장운영정보",  # info / 3 / 현물
    "JX0": "주식선물가격제한폭확대",  # data / 3 / 선물
    "K1_": "KOSPI거래원(K1)",  # info / 3 / 현물
    "k1_4ELW": "ELW거래원(k1)",  # data / 3 / ELW
    "K3_": "KOSDAQ체결(K3)",  # order / 5 / 현물
    "KH_": "KOSDAQ프로그램매매종목별(KH)",  # info / 4 / 현물
    "KM_": "KOSDAQ프로그램매매전체집계(KM)",  # info / 4 / 현물
    "KS_": "KOSDAQ우선호가(KS)",  # data / 4 / 현물
    "MK2": "US지수",  # data / 3 / 해외
    "NWS": "실시간 뉴스 제목 패킷",  # info / 4 / 현물
    "O01": "선물접수",  # order / 3 / 선물
    "OC0": "KOSPI200옵션체결(C0)",  # order / 3 / ETF
    "OD0": "KOSPI200옵션실시간상하한가(D0)",  # data / 3 / ETF
    "OH0": "KOSPI200옵션호가(H0)",  # data / 3 / ETF
    "OK_": "KOSDAQ거래원(OK)",  # info / 3 / 현물
    "OMG": "KOSPI200옵션민감도(MG)",  # data / 3 / ETF
    "OX0": "KOSPI200옵션가격제한폭확대(X0)",  # data / 3 / ETF
    "PH_": "KOSPI프로그램매매종목별(PH)",  # info / 3 / ETF
    "PM_": "KOSPI프로그램매매전체집계(PM)",  # info / 3 / ETF
    "S2_": "KOSPI우선호가(S2)",  # data / 4 / 현물
    "s2_4ELW": "ELW우선호가(s2)",  # data / 3 / ELW
    "S3_": "KOSPI체결(S3)",  # data / 5 / 현물
    "s3_4ELW": "ELW체결(s3)",  # data / 3 / ELW
    "S4_": "KOSPI기세(S4)",  # data / 3 / 현물
    "s4_ELW": "ELW기세(s4)",  # data / 3 / ELW
    "SC0": "주식주문접수",  # order / 5 / 현물
    "SC1": "주식주문체결",  # order / 5 / 현물
    "SC2": "주식주문정정",  # order / 4 / 현물
    "SC3": "주식주문취소",  # order / 4 / 현물
    "SC4": "주식주문거부",  # order / 4 / 현물
    "SHC": "상/하한가근접진입",  # data / 4 / 현물
    "SHD": "상/하한가근접이탈",  # data / 4 / 현물
    "SHI": "상/하한가진입",  # data / 4 / 현물
    "SHO": "상/하한가이탈",  # data / 4 / 현물
    "VI_": "VI발동해제",  # data / 3 / 현물
    "YC3": "상품선물예상체결",  # data / 3 / 선물
    "YFC": "지수선물예상체결",  # data / 3 / 선물
    "YJC": "주식선물예상체결",  # data / 3 / 선물
    "YJ_": "예상지수(YJ)",  # data / 3 / 현물
    "YK3": "KOSDAQ예상체결",  # data / 3 / 현물
    "YOC": "지수옵션예상체결",  # data / 3 / 현물
    "YS3": "KOSPI예상체결",  # data / 3 / 현물
    "Ys3_4ELW": "ELW예상체결(Ys3)"  # data / 3 / ELW
}